# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# https://fabricmc.net/2026/06/15/262.html
minecraft_version=26.2
yarn_mappings=1.21.11+build.6
loader_version=0.19.3
min_loader_version=0.19.3
# Mod Properties
mod_version=1.0
maven_group=win.lt404
archives_base_name=NoCheating
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.160.0+26.2
